name: Sync multiple branches
on:
  push:
    branches:
      - workflow-test
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge workflow-test -> landingpage
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: workflow-test
          target_branch: landingpage
          github_token: ${{ github.token }}
